# Config references:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: 
      interval: "daily"
    assignees:
      - "reside-eng/platform"
    reviewers:
      - "reside-eng/platform"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "reside-eng/platform"
    reviewers:
      - "reside-eng/platform"
