name: 'Workflow Status Slack Notification'
description: 'Notify upon workflow failure/success'
inputs:
  current-status:
    description: 'Status of the current run'
    required: true
    default: 'failure'
  slack-webhook:
    description: 'Webhook URL with token for notifications'
    required: true
    default: ''
  notify-type:
    description: 'Type of notification (on-state-change, release)'
    required: false
    default: 'on-state-change'
  github-token:
    description: 'Status of the current run'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
  post-if: 'success()'
