name: 'Workflow Status Slack Notification'
description: 'Notify uppon workflow failure/success'
inputs:
  current-status:
    description: 'Status of the current run'
    required: true
    default: 'failure'
  success-message:
    description: 'Message for successful runs'
    required: true
  error-message:
    description: 'Message for runs with errors'
    required: true
  slack-webhook:
    description: 'Webhook URL with token for notifications'
    required: true
    default: ''
  github-token:
    description: 'Status of the current run'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
  post-if: 'success()'
