name: 'Workflow Status Slack Notification'
description: 'Notify uppon workflow failure/success'
inputs:
  current-status:
    description: 'Status of the current run'
    required: true
    default: 'failure'
  slack-channel:
    description: 'Slack channel to send the notification to'
    required: false
    default: ''
  slack-webhook:
    description: 'Webhook URL with token for notifications'
    required: true
    default: ''
  github-token:
    description: 'Status of the current run'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
