name: 'Workflow Status Slack Notification'
description: 'Notify uppon workflow failure/success'
inputs:
  current-status:
    description: 'Status of the current run'
    required: true
    default: 'failure'
  slack-channel:
    description: 'Status of the current run'
    required: true
    default: ''
  slack-webhook:
    description: 'Status of the current run'
    required: true
    default: ''
  github-token:
    description: 'Status of the current run'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: last-run-status
        key: last-run-status-${{ github.run_id }}

    - name: Retrieve last runs from same run ID if exists
      shell: bash
      run: |
        if test -f "last-run-status"; then
          lastRunStatus=$(cat last-run-status)
        else
          lastRunStatus="first_run"
        fi
        echo "LAST_RUN_STATUS=$lastRunStatus" >> $GITHUB_ENV

    - name: Retrieve last runs status
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        if [[ "$LAST_RUN_STATUS" == 'first_run' ]]; then
          lastRunStatus=$( gh run list -w ${{ github.workflow }} | grep "${{ github.workflow }}	${{ github.head_ref }}" | grep -v "completed	cancelled" | grep -v "in_progress" | head -n 1 | awk -F" " '{print $1"/"$2}' )
          echo "LAST_RUN_STATUS=$lastRunStatus" >> $GITHUB_ENV
        fi

    - name: Store current run status
      shell: bash
      run: |
        echo "completed/${{ inputs.current-status }}" > last-run-status

    - name: Prepare Slack Notification
      shell: bash
      run: |
        if [[ ${{ inputs.current-status }} == 'success' && "$LAST_RUN_STATUS" == 'completed/failure' ]]; then
          echo "SLACK_CHANNEL=${{ inputs.slack-channel }}" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=Previously failing ${{ github.workflow }} workflow in ${{ github.repository }} succeed." >> $GITHUB_ENV
        elif [[ ${{ inputs.current-status }} == 'failure' && ( "$LAST_RUN_STATUS" == 'completed/success' || "$LAST_RUN_STATUS" == '' ) ]]; then
          echo "SLACK_CHANNEL=${{ inputs.slack-channel }}" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=${{ github.workflow }} workflow in ${{ github.repository }} failed." >> $GITHUB_ENV
        else
          echo "SLACK_CHANNEL=none" >> $GITHUB_ENV
          echo "SLACK_MESSAGE=none" >> $GITHUB_ENV
        fi

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
        SLACK_COLOR: '${{ inputs.current-status }}'
        SLACK_TITLE: '${{ github.workflow }} workflow ${{ inputs.current-status }}'
        SLACK_MESSAGE: '${{ env.SLACK_MESSAGE }}'
        SLACK_FOOTER: ''
